# Generated by Django 5.2.6 on 2025-09-09 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Normalized job title', max_length=200)),
                ('company', models.CharField(help_text='Normalized company name', max_length=100)),
                ('location', models.CharField(help_text='Normalized location', max_length=100)),
                ('description', models.TextField(help_text='Cleaned job description')),
                ('canonical_url', models.URLField(max_length=500)),
                ('first_seen', models.DateTimeField(help_text='When we first discovered this job')),
                ('last_seen', models.DateTimeField(help_text='When we last confirmed this job still exists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'location'], name='scraper_job_company_36f4ff_idx'), models.Index(fields=['first_seen'], name='scraper_job_first_s_6852fe_idx'), models.Index(fields=['last_seen'], name='scraper_job_last_se_03002b_idx')],
            },
        ),
        migrations.CreateModel(
            name='RawJobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_site', models.CharField(choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed')], help_text='Which site this was scraped from', max_length=50)),
                ('raw_title', models.TextField(help_text='Job title as it appears on the site')),
                ('raw_company', models.TextField(help_text='Company name as it appears on the site')),
                ('raw_location', models.TextField(help_text='Location as it appears on the site')),
                ('raw_description', models.TextField(help_text='Full job description')),
                ('source_url', models.URLField(help_text='Direct link to the job posting', max_length=500)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending Processing'), ('processed', 'Successfully Processed'), ('failed', 'Processing Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_site', 'scraped_at'], name='scraper_raw_source__68c381_idx'), models.Index(fields=['processing_status'], name='scraper_raw_process_bc2e9b_idx')],
                'unique_together': {('source_site', 'source_url')},
            },
        ),
        migrations.CreateModel(
            name='ScrapingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_site', models.CharField(max_length=50)),
                ('search_term', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('jobs_attempted', models.IntegerField(default=0)),
                ('jobs_successful', models.IntegerField(default=0)),
                ('jobs_failed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed Successfully'), ('failed', 'Failed'), ('partial', 'Partially Completed')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_site', 'started_at'], name='scraper_scr_source__3ed600_idx'), models.Index(fields=['status'], name='scraper_scr_status_b8ddc6_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(help_text='Jaccard similarity score (0.0 to 1.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_manual', models.BooleanField(default=False, help_text='True if a human manually verified this mapping')),
                ('canonical_job', models.ForeignKey(help_text='The canonical job this maps to', on_delete=django.db.models.deletion.CASCADE, to='scraper.job')),
                ('raw_posting', models.ForeignKey(help_text='The raw scraped posting', on_delete=django.db.models.deletion.CASCADE, to='scraper.rawjobposting')),
            ],
            options={
                'indexes': [models.Index(fields=['similarity_score'], name='scraper_job_similar_b9def1_idx'), models.Index(fields=['created_at'], name='scraper_job_created_96ecda_idx')],
                'unique_together': {('raw_posting', 'canonical_job')},
            },
        ),
    ]
